language: go
go: 1.5
sudo: false
os:
- linux
- osx
env: STACK_ARGS=""
addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - cabal-install-1.22
    - ghc-7.10.1
    - alex-3.1.4
    - happy-1.19.5
before_install:
- export PATH=/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin:$PATH
- export PATH=/opt/alex/3.1.4/bin:$PATH
- export PATH=/opt/happy/1.19.5/bin:$PATH
- export PATH=$HOME/.cabal/bin:$PATH

# Install OSX dependencies.
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ghc cabal-install pcre; fi

# Download and unpack the stack executable
- export PATH=/opt/ghc/7.10.1/bin:$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

install:
#- travis_retry cabal update
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config;
  #fi
#- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cabal install alex-3.1.4; cabal install happy-1.19.5; fi
#- cabal install hlint
#- cabal sandbox init
#- cabal install --enable-tests --only-dependencies
- stack --no-terminal --install-ghc $STACK_ARGS test --only-dependencies
script:
- stack build
- export VERSION=branch-$TRAVIS_BRANCH-job-$TRAVIS_JOB_NUMBER
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then export VERSION=pull-request-$TRAVIS_PULL_REQUEST-job-$TRAVIS_JOB_NUMBER;
  fi
- if [[ "$TRAVIS_TAG" != "" ]]; then export VERSION=$TRAVIS_TAG; fi
- make dist ci-test
cache:
  apt: true
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
deploy:
  provider: releases
  api_key:
    secure: f8vgUN0ng9BWeBO/WcNzIS11BDDyNF/qFHqs0WsxHnausDAC91O1VPEayDpNE5MUHIgLDgLGVl7NE34lHvVTnTVkC2drM8pXVVSSaS+ZSkaCajeMZ82nK30OK36MwUXpOu6FJ/zkRX+8hiQbysRemTvh+w4xXNTb7eBBMs+50wFmxB6oon3zLcd9uR1N8QQ9Vxor8Mb7W5KIkjFnUHPrxfw1KByUw+6rgug+OYoDRSLSCmxiULzPRWeHbKdtGvd9kNhXQQc9KCc8UGfkG0C/TPBdtXqRDoQ/4Szevy6zK8wNK/FyMuKAw1JtX7qy7IBtsQgkavqDKEz61+CxppBN92q+aWcS6QxuJ0nHhtJ82dWNRiM5/xoEC96/tHOgXU/VDNtfZttT68AwWurU4dgZxBwUPzcps2x+R076CVnyQZ+84m1KTTzFr0xCyI+rglmHca1REfqYdZ3/th6WRXUMjHROO6mM9ZNK4EgAAGRVJVYBsdIneMSjklaD32fgfmZnMqxKhOqWe2cOzK7yhrOy8BdUnIG8D7ihM2wyS3n/VG7FWI2LwZrZ7doV1v32wgLeCN0Eqqu5Gbx26BBCOD7k30ik7iGAd0VnDQ10vE6ccLNY9ACZYXdXMLLOBjuZ9UWFc3Udm5M5Z1vjCq0D0AGcTohHeSA4VA/LaaiDDM/pCEU=
  file: build/oden-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: oden-lang/oden
notifications:
  slack:
    secure: CzIDDPphI227LamRZdSmjyDZijMyJVBvtSpMKRh/S7C19T9HbwbD7DUh8Aiif5V4L4VFbd/Pp21/D7WPY4bf9+Iv7wVD9NAUwPaZ/elkk310bcqEuShSsGY8YhUwaz68CU89APLs318qSntE8X3YQ+xWp9NRJBw+eJXAosrKFWn8a29sJdbfGlhKU8pZ6OnUDIlXaX254zcr/OcQZl9dnrN20XsCuMN693gI1gKgA1fQyKC29wfUy7RICmOajq3pHKG9YDMdNnYJRddsw9Yh8h8xiICoTLE9Bb54GzZMTzm15/BSqhHTQ/wHQbDkKmjN0CQyuoexnaMX++oCHGg6Uz8pUNIMcIow8pAklqTKodqfB4r0rhMPrx7CC+ASLZp5bXp/AxocP7fINq/4XqP4ny4ufl8cuTJPt/1MgtOqisHIQhBk//duspAfcqGBT7sIN77Cd5FmbbTl7VpliZnvIhPVInZPpatBksQaQ7MOXkayjmBiQgzwS1SH3kX277WAI1boaV2LHlnRy2aACrMP7uBdp7EJjzsQVWLqUS4YM0UzBV8a/vlrisrAm+lMkzTt7QaJVOJEhTpK83o9qBx7OG5FIBovIl0q/4bcpsmL271H9jBvARFbF1/Ng9znvbvmYd8tEh6uZb5XfC+r9jURGnGFDKf2kP5SRHMEHN4wC/I=
